from pathlib import Path

import numpy as np


# Default parameters for each image database
DATABASE = {
    "data_path": {
        "gui_name": "Data path",
        "type": list,
        "min": None,
        "max": None,
        "default": [],
        "description": "List of folders with images files to correct",
    },
    "one_down": {
        "gui_name": "Look one level down",
        "type": bool, 
        "min": None,
        "max": None,
        "default": False,
        "description": "Whether to look in all subfolders when looking for image files"
    },
    "input_format": {
        "gui_name": "Input format",
        "type": str,
        "min": None,
        "max": None,
        "default": "tif",
        "description": "Can be ['tif', 'h5', 'nwb', 'bruker', 'movie', 'dcimg'].",
    },
    "nplanes": {
        "gui_name": "Number of planes",
        "type": int,
        "min": 1,
        "max": 100,
        "default": 1,
        "description": "Each tiff / file has this many planes in sequence.",
    },
     "nrois": {
        "gui_name": "Number of ROIs",
        "type": int,
        "min": 1,
        "max": 100,
        "default": 1,
        "description": "Each tiff / file has this many different ROIs.",
    },
    "nchannels": {
        "gui_name": "Number of channels",
        "type": int,
        "min": 1,
        "max": 2,
        "default": 1,
        "description": "Specify one- or two- channel recording.",
    },
    "swap_order": {
        "gui_name": "Swap the order of channels and planes for multiplexed recordings.",
        "type": bool,
        "min": None,
        "max": None,
        "default": False,
        "description": "Swap the order of channels and planes for multiplexed recordings.",
    },
    "lines": {
        "gui_name": "Lines for each ROI",
        "type": list,
        "min": None,
        "max": None,
        "default": None,
        "description": "Line numbers for each ROI.",
    },
    "dy": {
        "gui_name": "Y position for each ROI",
        "type": list,
        "min": None,
        "max": None,
        "default": None,
        "description": "Y position for each ROI.",
    },
    "dx": {
        "gui_name": "X position for each ROI",
        "type": list,
        "min": None,
        "max": None,
        "default": None,
        "description": "X position for each ROI.",
    },
    "subfolders": {
        "gui_name": "Subfolders",
        "type": list,
        "min": None,
        "max": None,
        "default": None,
        "description": "If len(data_path)==1, subfolders of data_path[0] to use when look_one_level_down is set to True.",
    },
    "file_list": {
        "gui_name": "File list",
        "type": list,
        "min": None,
        "max": None,
        "default": None,
        "description": "List of files to process (default is all files in data_path, only supported with one data_path folder).",
    },
    "save_path0": {
        "gui_name": "save_path0",
        "type": str,
        "min": None,
        "max": None,
        "default": None,
        "description": "Directory to store results, defaults to data_path[0].",
    },
    "fast_disk": {
        "gui_name": "Fast disk",
        "type": str,
        "min": None,
        "max": None,
        "default": None,
        "description": "Directory to store temporary binary file (recommended to be SSD), defaults to save_path0.",
    },
    "save_folder": {
        "gui_name": "Save folder",
        "type": str,
        "min": None,
        "max": None,
        "default": "corrected_images",
        "description": "Directory within save_path0 to save results.",
    },
    "h5py_key": {
        "gui_name": "h5py key",
        "type": str,
        "min": None,
        "max": None,
        "default": "data",
        "description": "Key in h5py where data array is stored.",
    },
    "force_sktiff": {
        "gui_name": "Force tifffile reader",
        "type": bool,
        "min": None,
        "max": None,
        "default": False,
        "description": "Use tifffile for tiff reading instead of scanimage-tiff-reader.",
    },
    "bruker_bidirectional": {
        "gui_name": "Bruker bidirectional",
        "type": bool,
        "min": None,
        "max": None,
        "default": False,
        "description": "Tiffs in 0, 1, 2, 2, 1, 0 ... order.",
    },
}

# Default settings for running the motion correction pipeline
SETTINGS = {
    "torch_device": {
        "gui_name": "Torch device",
        "type": str,
        "min": None,
        "max": None,
        "default": "cpu",
        "description": "Torch device using GPU ('cuda') or CPU ('cpu').",
    },
    "select_algorithm": {
        "gui_name": "Select algorithm",
        "type": str,
        "min": None,
        "max": None,
        "default": "Suite2p",
        "description": "Use Suite2p or PatwarpWarp for motion correction",
    },
    "downsampled_frames": {
        "gui_name": "Downsampled frame num.",
        "type": int,
        "min": 1,
        "max": 1000,
        "default": 50,
        "description": "Number of frames to downsample for summary video"
    },
    "suite2p_settings": {
        "align_by_chan2": {
            "gui_name": "Align by chan2 (non-func)",
            "type": bool,
            "min": None,
            "max": None,
            "default": False,
            "description": "When two-channel, you can align by chan2.",
        },
        "nimg_init": {
            "gui_name": "# of frames for refImg",
            "type": int,
            "min": 0,
            "max": np.inf,
            "default": 400,
            "description": "Number of subsampled frames for finding reference image - choose more if reference image is poor.",
        },
        "maxregshift": {
            "gui_name": "Max registration shift",
            "type": float,
            "min": 0.,
            "max": 1.,
            "default": 0.1,
            "description": "Max allowed registration shift, as a fraction of frame max(width and height).",
        },
        "do_bidiphase": {
            "gui_name": "Compute bidiphase offset",
            "type": bool,
            "min": None,
            "max": None,
            "default": False,
            "description": "Whether or not to compute bidirectional phase offset from recording and apply to all frames in recording (applies to 2P recordings only).",
        },
        "bidiphase": {
            "gui_name": "Bidiphase offset",
            "type": float,
            "min": 0,
            "max": np.inf,
            "default": 0.,
            "description": "Bidirectional phase offset from line scanning (set by user). Applied to all frames in recording.",
        },
        "batch_size": {
            "gui_name": "# of frames per batch",
            "type": int,
            "min": 1,
            "max": np.inf,
            "default": 100,
            "description": "Number of frames per batch - choose fewer if using GPU and running out of memory.",
        },
        "nonrigid": {
            "gui_name": "Use nonrigid registration",
            "type": bool,
            "min": None,
            "max": None,
            "default": True,
            "description": "Whether to use nonrigid registration.",
        },
        "maxregshiftNR": {
            "gui_name": "Nonrigid max pixel shift",
            "type": int,
            "min": 0,
            "max": np.inf,
            "default": 5,
            "description": "Maximum pixel shift allowed for nonrigid, relative to rigid, may need to increase value for unstable recordings.",
        },
        "block_size": {
            "gui_name": "Nonrigid block size",
            "type": tuple,
            "min": None,
            "max": None,
            "default": (128, 128),
            "description": "Block size for non-rigid registration (** keep this a multiple of 2, 3, and/or 5 **).",
        },
        "smooth_sigma_time": {
            "gui_name": "Time smoothing",
            "type": float,
            "min": 0.,
            "max": np.inf,
            "default": 0,
            "description": "Gaussian smoothing in time to compute registration shifts (may be necessary with low SNR).",
        },
        "smooth_sigma": {
            "gui_name": "Smoothing in XY",
            "type": float,
            "min": 0.25,
            "max": np.inf,
            "default": 1.15,
            "description": "Gaussian smoothing in XY; ~1 good for 2P recordings, 3-5 may work well for 1P recordings.",
        },
        "spatial_taper": {
            "gui_name": "Edge tapering width",
            "type": float,
            "min": 0.,
            "max": np.inf,
            "default": 3.45,
            "description": "Edge tapering width in pixels, may want larger for 1P recordings.",
        },
        "th_badframes": {
            "gui_name": "Bad frame threshold",
            "type": float,
            "min": 0.,
            "max": np.inf,
            "default": 1.,
            "description": "Determines which frames to exclude when determining cropping - set it smaller to exclude more frames, particularly if crop seems small.",
        },
        "norm_frames": {
            "gui_name": "Normalize frames",
            "type": bool,
            "min": None,
            "max": None,
            "default": True,
            "description": "Normalize frames when detecting shifts.",
        },
        "snr_thresh": {
            "gui_name": "Nonrigid SNR threshold",
            "type": float,
            "min": 1.,
            "max": np.inf,
            "default": 1.2,
            "description": "If any nonrigid block is below this threshold, it gets smoothed until above this threshold. 1.0 results in no smoothing.",
        },
        "subpixel": {
            "gui_name": "Nonrigid subpixel reg",
            "type": int,
            "min": 1,
            "max": 100,
            "default": 10,
            "description": "Precision of subpixel registration for nonrigid (1/subpixel steps).",
        },
        "upsample_meanImg": {
            "gui_name": "Upsample meanImg",
            "type": list,
            "min": None,
            "max": None,
            "default": None,
            "description": "Upsampling factor for super-resolution meanImg computation. If 0 or None, no upsampling is performed.",
        },

    },
    "Patchwarp_settings": {
        "align_by_chan2": {
            "gui_name": "Align by chan2 (non-func)",
            "type": bool,
            "min": None,
            "max": None,
            "default": False,
            "description": "When two-channel, you can align by chan2.",
        },
        "do_rigid": {
            "gui_name": "Perform rigid motion correction",
            "type": bool,
            "min": None,
            "max": None,
            "default": True,
            "description": "Whether to perform rigid motion correction"
        },
        "do_nonrigid": {
            "gui_name": "Peform nonridig motion correction",
            "type": bool,
            "min": None,
            "max": None,
            "default": True,
            "description": "Whether to perform nonrigid motion correction"
        },
        "rigid_norm_method": {
            "gui_name": "Rigid norm. method",
            "type": str,
            "min": None,
            "max": None,
            "default": "rank",
            "description": "Rigid normalization method. Try 'local' when 'rigid' does not work well",
        },
        "rigid_norm_radius": {
            "gui_name": "Rigid norm. radius",
            "type": int,
            "min": 5,
            "max": 120,
            "default": 32,
            "description": "Radius of circular filter for 'local' normalization method",
        },
        "rigid_template_tiffstack_num": {
            "gui_name": "Rigid template number",
            "type": int,
            "min": 2,
            "max": 100,
            "default": 5,
            "description": "Number of image stacks (files) to estimate template images",
        },
        "rigid_template_block_size": {
            "gui_name": "Rigid template block size",
            "type": int,
            "min": 1,
            "max": 11,
            "default": 5,
            "description": "Number of image blocks per imaging session to split for rigid correction",
        },
        "rigid_template_threshold": {
            "gui_name": "Rigid template threshold",
            "type": float,
            "min": 0.1,
            "max": 0.9,
            "default": 0.2,
            "description": "Quantile threshold for selecting frames used for template image",
        },
        "rigid_template_center_frac": {
            "gui_name": "Rigid template center frac.",
            "type": float,
            "min": 0.1,
            "max": 0.9,
            "default": 0.8,
            "description": "Central fraction of template used for registration",
        },
        "rigid_template_fftdenoise": {
            "gui_name": "Rigid template denoise",
            "type": bool,
            "min": None,
            "max": None,
            "default": False,
            "description": "Remove strong period noise (i.e., ripple PMT noise) from the template image",
        },
        "nonrigid_transform": {
            "gui_name": "Nonrigid transform",
            "type": str,
            "min": None,
            "max": None,
            "default": "affine",
            "description": "Type of transform for nonrigid correction (affine, translation, euclidean, homography)",
        },
        "affine_norm_radius": {
            "gui_name": "Affine norm. radius",
            "type": int,
            "min": 4,
            "max": 120,
            "default": 32,
            "description": "Radius of circular filter used for local intensity normalization",
        },
        "warp_pyramid_levels": {
            "gui_name": "Warp pyramid levels",
            "type": int,
            "min": 1,
            "max": 10,
            "default": 1,
            "description": "Number of levels in pyramid scheme (1 for non pyramid implamentation)",
        },
        "warp_pyramid_iterations": {
            "gui_name": "Warp pyramid iterations",
            "type": int,
            "min": 1,
            "max": 500,
            "default": 50,
            "description": "Number of iterations per level",
        },
        "warp_template_stack_num": {
            "gui_name": "Warp template stack num",
            "type": int,
            "min": 1,
            "max": 100,
            "default": 5,
            "description": "Number of image blocks per imaging session to split for nonrigid correction",
        },
        "warp_block_size": {
            "gui_name": "Warp block size",
            "type": int,
            "min": 1,
            "max": 50,
            "default": 5,
            "description": "Row and column numbers for splitting FOV for estimating transformation matrices",
        },
        "warp_overlap_pix_frac": {
            "gui_name": "Warp overlap pixel frac.",
            "type": float,
            "min": 0.0,
            "max": 1.0,
            "default": 0.15,
            "description": "Fraction of edge pixels that overlaps with the adjacent patches.",
        },
        "warp_remove_edge_pix": {
            "gui_name": "Warp remove edge pix",
            "type": int,
            "min": 0,
            "max": 100,
            "default": 0,
            "description": "Number of pixels to ignore from the lateral edges of FOV.",
        },
        "warp_split_num": {
            "gui_name": "Warp split number",
            "type": int,
            "min": 0,
            "max": 100,
            "default": 6,
            "description": "Sessions are split to this number, and initial affine transformation matrices are re-estimated for each block",
        },
        "affine_rho_threshold": {
            "gui_name": "Affine rho threshold",
            "type": float,
            "min": 0.0,
            "max": 1.0,
            "default": 0.5,
            "description": "If corr. coef. between template and subfield is less than this threshold, will be ignored before filtering",
        },
        "affine_medfilt_stack_num": {
            "gui_name": "Affine filtering stack num.",
            "type": int,
            "min": 1,
            "max": 100,
            "default": 1,
            "description": "Window size (number of tif stack files) that are used for median temporal filtering of affine transformation matrices.",
        },
        "affine_abssum_threshold": {
            "gui_name": "Affine abs sum threshold",
            "type": int,
            "min": 1,
            "max": 1000,
            "default": 50,
            "description": "If the sum of absolute values of all elements in an estimated affine transformation matrix exceeds affinematrix_abssum_threshold, the matrix will be ignored before median temporal filtering.",
        },
        "affine_abssum_jump_threshold": {
            "gui_name": "Affine abs sum jump threshold",
            "type": int,
            "min": 1,
            "max": 1000,
            "default": 10,
            "description": "Ignore estimated affine matrices when the estimated matrix is very different from the matrix from the adjacent frame.",
        },
    },
}
